# parking_occupancy/config/slot_b1.yaml
fixed_slots_m:
  - [-3.79980206489563, -0.8791968822479248, 100.3132739624956, 0.80, 0.80]
  - [-2.910674571990967, -0.7003345489501953, 100.31324664173893, 0.80, 0.80]
  - [-2.0080323219299316, -0.5019452571868896, 101.99794012127923, 0.80, 0.90]

